<a href="https://colab.research.google.com/github/MdShahadatHossainbd/Machine-Learning/blob/main/1_Linear_Regression_Multiple_Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [23]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [24]:
df.bedrooms.median()

4.0

In [25]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

4

In [26]:
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    4.0
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [27]:
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [28]:
reg = linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [29]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [30]:
reg.intercept_

221323.00186540396

Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old

In [31]:
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [32]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 221323.00186540384

498408.25157402386

In [33]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])